[project]
name = "equipdata-fiscaliza-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "coloredlogs>=15.0.1",
    "keyboard>=0.13.5",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "python-redmine>=2.5.0",
]
